name: "CI"

on:
  push:

jobs:
  quality:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup Biome"
        uses: biomejs/setup-biome@v2
        with:
          version: 2
      - name: "Run Biome"
        run: "biome ci ."
  test:
    runs-on: ubuntu:latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"
      - name: "Install deps"
        run: "bun install --frozen-lockfile"
      - name: "Run test"
        run: "bun test"
